version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ibge
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://admin:admin@db:5432/ibge
      DATA_DIR: /data
      APP_TIMEZONE: America/Sao_Paulo
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./data:/data
    command: uvicorn main:app --host 0.0.0.0 --port 8000


volumes:
  pgdata:
