services:
  db:
    image: postgres:16
    container_name: ibge-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ibge
      TZ: America/Sao_Paulo
    command: ["postgres", "-c", "shared_buffers=256MB", "-c", "max_connections=200"]
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ibge || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ibge-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://admin:admin@db:5432/ibge
      TZ: America/Sao_Paulo
      PYTHONUNBUFFERED: "1"
      PORT: "8000"
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
    restart: unless-stopped

volumes:
  pgdata:
